CREATE TABLE IF NOT EXISTS StopLeveL_NFR (  
FileName TEXT  
,ExportDate TEXT  
,PlanTo TIMESTAMP 
,TenderStatus TEXT  
,OrderType TEXT 
,Mode TEXT  
,EqpGrp TEXT  
,Carrier TEXT 
,CarrierType TEXT 
,BusUnit TEXT 
,ShipmentId TEXT  
,OrderIds TEXT  
,IsMultiStop INTEGER  
,ShipStopCount INTEGER  
,IsShipLastStop INTEGER 
,StopNum INTEGER  
,StopType TEXT  
,IsSpotCost TEXT  
,DriverId TEXT  
,DriverName TEXT  
,ApptStart TIMESTAMP  
,ApptEnd TIMESTAMP  
,StartDate TIMESTAMP  
,StartTime TIMESTAMP  
,EndTime TIMESTAMP  
,ApptPickup TIMESTAMP 
,ApptDeliv TIMESTAMP  
,PlanArrive TIMESTAMP 
,PlanDepart TIMESTAMP 
,ActualArrive TIMESTAMP 
,ActualDepart TIMESTAMP 
,OnTimePickUp TEXT  
,OnTimeDeliv TEXT 
,SrcCode TEXT 
,SrcName TEXT 
,SrcCity TEXT 
,SrcState TEXT  
,SrcCityState TEXT  
,SrcZip TEXT  
,SrcIsDgPlant INTEGER 
,DestCode TEXT  
,DestName TEXT  
,DestCity TEXT  
,DestState TEXT 
,DestCityState TEXT 
,DestZip TEXT 
,Lane TEXT  
,UnitCount INTEGER  
,GrossWt REAL 
,NetWt REAL 
,WtUtilization REAL 
,DistFromPrev REAL  
,DistUnload REAL  
,DistLoad REAL  
,DistTot REAL 
,AccsCost REAL  
,FuelCost REAL  
,LineHaul REAl  
,AcceptCost REAL  
,TotCost REAL 
,GlCost REAL  
);  
CREATE INDEX FileNameIx ON StopLevel_NFR (FileName); 
CREATE INDEX ShipmentIdIx ON StopLevel_NFR (ShipmentId);
